### PR TITLE
Support for React 0.14.7

### PR DESCRIPTION
**Pull request by dclowd9901**
Love,

Your friends at Jama

### CODE REVIEW

**Comment by browniefed** [comment]
Published, may want to look at pulling this into gitlab and using nexus for a proxy ;)

**Comment by dclowd9901** [comment]
Wanted to give you first priority :D But if you're dropping support, we'll go ahead and do that.

**Comment by wintermuted** [comment]
:+1:

**Comment by browniefed** [comment]
Shouldn't need much maintenance moving forward since react-dom ain't going away, so I'll maintain it for awhile.

**Pull request merged**
